version: "3.7"
services:
  db:
    image: mariadb:10.5
    volumes:
      - dbvolume:/var/lib/mysql
    env_file: development.env
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/huntogether
      - gem_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: development.env
    stdin_open: true
    tty: true
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
volumes:
  dbvolume:
  gem_data: